### ISSUE TITLE
【SSL設定】docker-compose： nginx-proxyの設定

### ISSUE THREAD

**Issue by urashin** [dx-junkyard/proxy-sbh-nginx#1]
以下のように変更

```
  nginx-proxy:
    image: nginx:latest
    restart: always
    volumes:
      - "$PWD/nginx.config/:/etc/nginx/conf.d/"
      - "$PWD/localhost.pem:/path/to/fullchain.pem"
      - "$PWD/localhost-key.pem:/path/to/privkey.pem"
    ports:
      - "443:443"
```
